# Generated by Django 2.1.7 on 2019-04-17 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazyn', '0004_transakcja'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produkt',
            options={'ordering': ['nazwa']},
        ),
        migrations.AlterModelOptions(
            name='surowiec',
            options={'ordering': ['nazwa']},
        ),
        migrations.AlterModelOptions(
            name='wyrob',
            options={'ordering': ['nazwa']},
        ),
    ]
